### ISSUE TITLE
software not detected

### ISSUE THREAD

**Issue by ortizfr1966** [tim-lebedkov/npackd-cpp#53] opened 2020-05-06 22:30 UTC
Hello
I'm testing your software, and I'm having some issues.
Npackd does not detect software that I install outside of Npackd updates.
For example, I installed version 3.0.10 of VLC directly from the VLC site while Npackd did not yet offer this version. Npackd now offers version 3.0.10 but he believes that I am still under version 3.0.8 of VLC.
Do you have a solution ?
Thank you, I find your software very interesting, I test it and I try to understand how it works for 15 days, It has small "bugs" but very interesting.
Thank you again for making such software available to us.
I don't speak English very well, so this is google traslate which translates.
I speak French ++++, español ++++, portugues ++, italiano ++.

**Comment by tim-lebedkov** [comment] 2020-05-17 08:58
Your solution works, but is surely a hack. 

I don't speak any of the languages you listed. We have to stick to English.

**Comment by tim-lebedkov** [comment] 2020-05-17 08:59
Duplicate of #36

**Closed as completed by tim-lebedkov** 2020-05-17 08:59 UTC
Labels: duplicate
