### ISSUE TITLE
add a npackd service

### ISSUE THREAD

**Issue by Mannshoch** [tim-lebedkov/npackd-cpp#40] opened 2019-05-31 17:55 UTC
Please add a npackd service which allow to auto update Software

It should allow adding also a delay. So you could say:
"If a new software is found wait 2 Weeks and Update then if no additional software update is found."

That would allow to be on a more secure way to not be an early adopter of every update.

**Comment by tim-lebedkov** [comment] 2019-08-23 19:59
Duplicate of #27

**Closed as completed by tim-lebedkov** 2019-08-23 19:59 UTC
